name: cron_workflow

on:
  schedule:
    - cron:  '0,15,30,45 19-23 * * *'
    
jobs:
  cron-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world pour commencer 
        run: |
            echo "Hello frens"