name: push_toto

on:
  push:
    branches: toto

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: ls -larth

      - run: pwd

      - name: Run my Action
        id: run-action
        uses: parapente-dans-le-nord/test-action@main
        with:
          milliseconds: 1000

      - name: Print Output
        id: output
        run: echo "${{ steps.run-action.outputs.time }}"