
name: push_toto

on:
  push:
    branches: toto
    
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: ls -larth

      - run: pwd
        
      - name: Hello world action step
        uses: /home/runner/work/github-actions-testing/github-actions-testing/.github/actions/hello-world-action
        id: hello
        with:
          who-to-greet: 'Manu le ouf'

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"