
name: push_toto

on:
  push:
    branches: toto
    
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world action step
        uses: ./
        id: hello
        with:
          who-to-greet: 'Manu le ouf'

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"