name: spots_creator_with_issue
on:
  issues:
    types: [opened, edited]
jobs:
  addSpot:
    # if: creator = alain ou moi
    # gestion des erreurs : texte dans l'issue qui demande a faire les modifs
    # pousse en ftp juste spot.json

    if: contains( github.event.issue.labels.*.name, 'addSpot')

    permissions:
      contents: write
      pull-requests: write
      issues: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: parse issue and add spot to spots.json
        id: run-action-docker
        uses: parapente-dans-le-nord/dockerized-github-action@main
        with:
          issueBody: ${{ github.event.issue.body }}

      - name: dynamic branch name
        id: dynamic-branch-name
        run: echo "BRANCH_NAME=feature_$(date +'%H%M%S')" >> $GITHUB_ENV

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: add spot from actions
          branch: ${{ env.BRANCH_NAME }}
          create_branch: true

      - name: create pull request
        run: gh pr create -B main -H ${{ env.BRANCH_NAME }} --title 'Merge ${{ env.BRANCH_NAME }} into main' --body 'Created by Github action'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: merge pull request
        run: gh pr merge ${{ env.BRANCH_NAME }} --merge --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: push spots.json on server
        run: curl -u ${{ secrets.FTPUSER}}:${{ secrets.FTPPASSWORD }} -T src/spots.json ftp://ftp.cluster007.hosting.ovh.net/www/meteonew/

      - run: gh issue comment $ISSUE --body "Le spot est ajouté !!!"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}