name: spots_creator_with_issue
on:
  issues:
    types: [opened, edited]
jobs:
  addSpot:
    # if: creator = alain ou moi
    if: contains( github.event.issue.labels.*.name, 'addSpot')

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: parse issue and add spot to spots.json
        id: run-action-docker
        uses: parapente-dans-le-nord/dockerized-github-action@main
        with:
          issueBody: ${{ github.event.issue.body }}

      
#      - run: gh issue comment $ISSUE --body "Thank you for opening this issue!"
#        env:
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          ISSUE: ${{ github.event.issue.html_url }}