name: spots_creator_with_issue
on:
  issues:
    types: [opened, edited]
jobs:
  addSpot:
    if: contains( github.event.issue.labels.*.name, 'addSpot')

    runs-on: ubuntu-latest
    steps:
      - name: label addSpot ok ?
        run: echo "we have the good label"

      
#      - run: gh issue comment $ISSUE --body "Thank you for opening this issue!"
#        env:
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          ISSUE: ${{ github.event.issue.html_url }}