on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - run: |
          echo "VERSION=$(cat src/version.txt)" >> $GITHUB_ENV

      - run: |
          echo "la valeur dans le fichier -> ${{ env.VERSION }}"
      
      - name : If version anything except tata
        if: ${{ env.VERSION != 'tata' }}
        run: |
          echo "All good je peux faire un tag avec ta version"