on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'hello world'
      - uses: actions/checkout@v4
      - run: |
          echo "MyVar=$(cat src/test.txt)" >> $GITHUB_ENV
      - run: |
          echo "la valeur dans le fichier -> ${MyVar}"